config/routes.rb
Rails.application.routes.draw do
  get 'carts/show'
  get 'cart_items/new'
  resources :products
  root 'top#main'
  get'top/main'
  resources :cart_items, only: [:new, :create, :destroy]
  resources :carts, only: [:show]
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_cart
    private
    def current_cart
        if session[:cart_id]
            cart = Cart.find(session[:cart_id])
        else
            cart = Cart.create
            session[:cart_id] = cart.id
        end
        cart
    end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
    def new
        @cart_id = current_cart.id
        @product_id = params[:product_id]
        @cart_item = CartItem.new
    end
    
    def create
        @cart_id = params[:cart_item][:cart_id]
        @product_id = params[:cart_item][:product_id]
        @qty = params[:cart_item][:qty]
        c = CartItem.new(cart_id: @cart_id, product_id: @product_id, qty: @qty)
        if c.save
            redirect_to carts_show_path
        else
            render "new"
        end
    end
    
    def destroy
        CartItem.find(params[:id]).destroy
        redirect_to root_path
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    def show
      @cart_items = CartItem.where(cart_id: current_cart.id)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end
  
  def new
    @product = Product.new
  end
  
  def create
    product = Product.new(name: params[:product][:name], price: params[:product][:price])
    product.save
    redirect_to root_path
  end
  
  def destroy
    Product.find(params[:id]).destroy
    redirect_to root_path
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
    def main
        redirect_to products_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/cart_items/new.html.erb
<h1>カートに入れる</h1>
<%= form_for @cart_item,url: {action: :create} do |f| %>
    <%= Product.find(@product_id).name %>
    <%= f.label :qty, '数量' %>
    <%= f.text_field :qty %>
    <%= f.hidden_field :product_id, value: @product_id %>
    <%= f.hidden_field :cart_id, value: @cart_id %>
    <%= f.submit 'カートに登録する' %>
<% end %>

app/views/carts/show.html.erb
<% @cart_items.each do |e| %>
<p>
    商品<%= e.product_id %>
    数量<%=e.qty %>
</p>
<% end %>
<%= link_to '商品一覧', products_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>L621</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<h1>商品一覧</h1>
<% @products.each do |e| %>
    <p>
    商品：<%= e.name %>
    価格：<%= e.price %>
    <%= link_to '商品を削除する', product_path(e), data: {"turbo-method": :delete} %>
    <%= link_to 'カートに入れる', cart_items_new_path(product_id: e.id) %>
    </p>
<% end %>
<%= link_to '商品を追加する', new_product_path %><br>
<%= link_to 'カートを見る', carts_show_path %>

app/views/products/new.html.erb
<h1>商品登録</h1>
<%= form_for @product,url: {action: :create} do |f| %>
    <%= f.label :name, '商品名' %>
    <%= f.text_field :name %><br>
    <%= f.label :price, '価格' %>
    <%= f.text_field :price %><br>
    <%= f.submit '登録' %>
<% end %>